// https://github.com/asciidwango/js-primer/issues/1011 の重複辞書チェック
const pattern = [
    "エディタ",
    "エントリ",
    "クオート",
    "サーバ",
    "コンストラクター",
    "フィルタ",
    "ユーザ",
    "あきらか",
    "いま",
    "閏年",
    "かっこ",
    "括弧",
    "擬似",
    "毎",
    "さい",
    "さき",
    "先程",
    "全て",
    "付ける",
    "時",
    "所",
    "通り",
    "なか",
    "なに",
    "始め",
    "ひと",
    "方",
    "かた",
    "もと",
    "やりとり",
    "りんご",
    "訳",
    "当てはめる",
    "溢れる",
    "あらわす",
    "いれる",
    "受けとり",
    "おこなう",
    "おす",
    "おわる",
    "かかわる",
    "気付く",
    "下さい",
    "ことなる",
    "すぎる",
    "過ぎない",
    "辿る",
    "だす",
    "繋ぐ",
    "出来る",
    "取りだす",
    "なおす",
    "なげる",
    "はいる",
    "ひらく",
    "まつ",
    "みる",
    "もつ",
    "もとづく",
    "よぶ",
    "分かる",
    "わける",
    "わたす",
    "上手く",
    "嬉しい",
    "素晴らしい",
    "むずかしい",
    "易い",
    "あらためて",
    "かならず",
    "既に",
    "ふたたび",
    "殆ど",
    "全く",
    "元々"
];
const fs = require("fs");
const path = require("path");
const prh = fs.readFileSync("prh.yml", "utf-8");
const techbooster = fs.readFileSync(path.join(__dirname, "../test/techbooster.yml", "utf-8"));
pattern.forEach(item => {
    if (prh.includes(item)) {
        console.log(item, " => prh");
    }
    if (techbooster.includes(item)) {
        console.log(item, " => techbooster");
    }
});